// Responsibility: render()'s own text format, independent of diff()'s plan
// shape. Boundary: the D1 uppercase-BEGIN/END rewrite is covered in
// trigger-migration.test.ts.
import { test } from "vitest";
import assert from "node:assert/strict";
import { render } from "../src/build/migration.ts";

test("render() trims each statement, joins them with a newline each, and omits the rebuild header by default", () => {
  const file = render(1, "x", ["  create table a (id)\n", "create table b (id)  "]);
  assert.deepEqual(file, {
    filename: "0001_x.sql",
    sql: '-- Migration 0001_x.sql. Generated by solarsql from the declared schema.\n'
      + 'create table a (id);\n'
      + 'create table b (id);\n',
  });
});
