-- Migration 0003_views_and_triggers.sql. Generated by solarsql from the declared schema.
alter table "orders" add column updated_at text;
CREATE VIEW confirmed_orders as
  select o.id, o.customer_id, c.name as customer_name
  from orders o join customers c on c.id = o.customer_id
  where o.status = 'confirmed';
CREATE TRIGGER orders_touch after update on orders
  BEGIN
    update orders set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') where id = new.id;
  END;
