-- Migration 0004_search.sql. Generated by solarsql from the declared schema.
CREATE VIRTUAL TABLE order_search using fts5(order_id unindexed, note);
CREATE TRIGGER order_search_insert after insert on orders
  BEGIN
    insert into order_search (order_id, note) values (new.id, new.note);
  END;
CREATE TRIGGER order_search_update after update of note on orders
  BEGIN
    delete from order_search where order_id = new.id;
    insert into order_search (order_id, note) values (new.id, new.note);
  END;
