-- Migration 0005_customer_name_not_empty.sql. Generated by solarsql from the declared schema.
pragma defer_foreign_keys = on;
drop view "confirmed_orders";
CREATE TABLE "_solarsql_new_customers" (
    id text primary key not null,
    name text not null check (length(name) > 0),
    email text not null unique
  ) strict;
create table "_solarsql_copy_customers" as select "id", "name", "email" from "customers";
drop table "customers";
alter table "_solarsql_new_customers" rename to "customers";
insert into "customers" ("id", "name", "email") select "id", "name", "email" from "_solarsql_copy_customers";
drop table "_solarsql_copy_customers";
CREATE VIEW confirmed_orders as
  select o.id, o.customer_id, c.name as customer_name
  from orders o join customers c on c.id = o.customer_id
  where o.status = 'confirmed';
