// Generated by solarsql build. Do not edit.
// The migration files, for a Durable Object to apply with migrate().

export const migrations = [
  { name: "0001_initial.sql", sql: "-- Migration 0001_initial.sql. Generated by solarsql from the declared schema.\nCREATE TABLE customers (\n    id text primary key not null,\n    name text not null,\n    email text not null unique\n  );\nCREATE TABLE order_lines (\n    id text primary key not null,\n    order_id text not null references orders(id),\n    sku text not null,\n    qty integer not null check (qty > 0),\n    price real not null\n  );\nCREATE TABLE orders (\n    id text primary key not null,\n    customer_id text not null references customers(id),\n    status text not null check (status in ('draft', 'confirmed')),\n    note text\n  );\nCREATE TABLE solarsql_assert (name text not null, ok integer not null);\nCREATE INDEX order_lines_order_id on order_lines (order_id);\nCREATE TRIGGER solarsql_assert_check before insert on solarsql_assert\n  when new.ok = 0\nbegin\n  select raise(abort, new.name);\nend;\n" },
] as const;
