// Generated by solarsql build. Do not edit.
// Module orders.
import type { Id, Meta, SqlValue } from "../../../src/index.ts";
import type { CustomersId } from "../customers/solarsql.generated.ts";

// The id of a row of order_lines.
export type OrderLinesId = Id<"order_lines">;
// The id of a row of orders.
export type OrdersId = Id<"orders">;

export type Generated = {
  /** One order, or none. */
  "\n    -- One order, or none.\n    select id, customer_id, status, note from orders where id = :id": {
    params: { id: OrdersId };
    row: { id: OrdersId; customer_id: CustomersId; status: "draft" | "confirmed"; note: string | null };
  };
  /** One order with its lines as an array. Empty when it has none. */
  "\n    -- One order with its lines as an array. Empty when it has none.\n    select o.id, o.status,\n      coalesce(json_group_array(json_object('id', l.id, 'sku', l.sku, 'qty', l.qty, 'price', l.price))\n        filter (where l.id is not null), '[]') as lines\n    from orders o\n    left join order_lines l on l.order_id = o.id\n    where o.id = :id\n    group by o.id": {
    params: { id: OrdersId };
    row: { id: OrdersId; status: "draft" | "confirmed"; lines: Array<{ "id": OrderLinesId; "sku": string; "qty": number; "price": number }> };
  };
  /** The orders of one customer, newest id first. */
  "\n    -- The orders of one customer, newest id first.\n    select id, status from orders where customer_id = :customer_id order by id desc": {
    params: { customer_id: CustomersId };
    row: { id: OrdersId; status: "draft" | "confirmed" };
  };
  "insert into orders (id, customer_id, status) values (:id, :customer_id, 'draft')": {
    params: { id: OrdersId; customer_id: CustomersId };
    row: {};
  };
  "insert into order_lines (id, order_id, sku, qty, price)\n       select value ->> 'id', :id, value ->> 'sku', value ->> 'qty', value ->> 'price' from json_each(:lines)": {
    params: { id: OrdersId; lines: SqlValue };
    row: {};
  };
  "select id, customer_id, status, note from orders where id = :id": {
    params: { id: OrdersId };
    row: { id: OrdersId; customer_id: CustomersId; status: "draft" | "confirmed"; note: string | null };
  };
  "exists (select 1 from order_lines where order_id = :id)": {
    params: { id: OrdersId };
    row: {};
  };
  "update orders set status = 'confirmed' where id = :id and status = 'draft'": {
    params: { id: OrdersId };
    row: {};
  };
  "changes() = 1": {
    params: {};
    row: {};
  };
  "update orders set note = :note where id = :id": {
    params: { note: string | null; id: OrdersId };
    row: {};
  };
};

export const generated: Meta<Generated> = {
  "\n    -- One order, or none.\n    select id, customer_id, status, note from orders where id = :id": { params: ["id"], json: [] },
  "\n    -- One order with its lines as an array. Empty when it has none.\n    select o.id, o.status,\n      coalesce(json_group_array(json_object('id', l.id, 'sku', l.sku, 'qty', l.qty, 'price', l.price))\n        filter (where l.id is not null), '[]') as lines\n    from orders o\n    left join order_lines l on l.order_id = o.id\n    where o.id = :id\n    group by o.id": { params: ["id"], json: ["lines"] },
  "\n    -- The orders of one customer, newest id first.\n    select id, status from orders where customer_id = :customer_id order by id desc": { params: ["customer_id"], json: [] },
  "insert into orders (id, customer_id, status) values (:id, :customer_id, 'draft')": { params: ["id", "customer_id"], json: [] },
  "insert into order_lines (id, order_id, sku, qty, price)\n       select value ->> 'id', :id, value ->> 'sku', value ->> 'qty', value ->> 'price' from json_each(:lines)": { params: ["id", "lines"], json: [] },
  "select id, customer_id, status, note from orders where id = :id": { params: ["id"], json: [] },
  "exists (select 1 from order_lines where order_id = :id)": { params: ["id"], json: [] },
  "update orders set status = 'confirmed' where id = :id and status = 'draft'": { params: ["id"], json: [] },
  "changes() = 1": { params: [], json: [] },
  "update orders set note = :note where id = :id": { params: ["note", "id"], json: [] },
};
