// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module orders.
import type { Id, Meta } from "../../../src/index.ts";
import type { CustomersId } from "../customers/solarsql.generated.ts";

// The id of a row of order_lines.
export type OrderLinesId = Id<"order_lines">;
// The id of a row of orders.
export type OrdersId = Id<"orders">;

export type Generated = {
  "insert into orders (id, customer_id, status) values (:id, :customer_id, 'draft')": {
    params: { id: OrdersId; customer_id: CustomersId };
    row: {};
  };
  "insert into order_lines (id, order_id, sku, qty, price)\n       select value ->> 'id', :id, value ->> 'sku', value ->> 'qty', value ->> 'price' from json_each(:lines)": {
    params: { id: OrdersId; lines: readonly { "id": OrderLinesId; "sku": string; "qty": number; "price": number }[] };
    row: {};
  };
  "select id, customer_id, status, note from orders where id = :id": {
    params: { id: OrdersId };
    row: { id: OrdersId; customer_id: CustomersId; status: "draft" | "confirmed"; note: string | null };
  };
  "exists (select 1 from order_lines where order_id = :id)": {
    params: { id: OrdersId };
    row: {};
  };
  "update orders set status = 'confirmed' where id = :id and status = 'draft'": {
    params: { id: OrdersId };
    row: {};
  };
  "changes() = 1": {
    params: {};
    row: {};
  };
  "update orders set note = :note where id = :id": {
    params: { note: string | null; id: OrdersId };
    row: {};
  };
  "select id, note, updated_at from orders where id = :id": {
    params: { id: OrdersId };
    row: { id: OrdersId; note: string | null; updated_at: string | null };
  };
  "update order_lines\n       set price = (select value ->> 'price' from json_each(:lines) where value ->> 'id' = order_lines.id)\n       where order_id = :id and id in (select value ->> 'id' from json_each(:lines))": {
    params: { lines: readonly { "price": number; "id": OrderLinesId }[]; id: OrdersId };
    row: {};
  };
  "changes() = json_array_length(:lines)": {
    params: { lines: readonly { "price": number; "id": OrderLinesId }[] };
    row: {};
  };
  /** One order, or none. */
  "\n    -- One order, or none.\n    select id, customer_id, status, note from orders where id = :id": {
    params: { id: OrdersId };
    row: { id: OrdersId; customer_id: CustomersId; status: "draft" | "confirmed"; note: string | null };
  };
  /** One order with its lines as an array. Empty when it has none. */
  "\n    -- One order with its lines as an array. Empty when it has none.\n    select o.id, o.status,\n      coalesce(json_group_array(json_object('id', l.id, 'sku', l.sku, 'qty', l.qty, 'price', l.price))\n        filter (where l.id is not null), '[]') as lines\n    from orders o\n    left join order_lines l on l.order_id = o.id\n    where o.id = :id\n    group by o.id": {
    params: { id: OrdersId };
    row: { id: OrdersId; status: "draft" | "confirmed"; lines: Array<{ "id": OrderLinesId; "sku": string; "qty": number; "price": number }> };
  };
  /** The orders of one customer, newest id first. */
  "\n    -- The orders of one customer, newest id first.\n    select id, status from orders where customer_id = :customer_id order by id desc": {
    params: { customer_id: CustomersId };
    row: { id: OrdersId; status: "draft" | "confirmed" };
  };
  /** The orders with the given ids. One parameter carries the whole list, so the list can be longer than the 100 bound values D1 allows. */
  "\n    -- The orders with the given ids. One parameter carries the whole list,\n    -- so the list can be longer than the 100 bound values D1 allows.\n    select id, status from orders where id in (select value from json_each(:ids)) order by id": {
    params: { ids: readonly OrdersId[] };
    row: { id: OrdersId; status: "draft" | "confirmed" };
  };
  /** Orders of one customer, with an optional status and a chosen order. */
  "\n    -- Orders of one customer, with an optional status and a chosen order.\n    select id, status, note from orders\n    where customer_id = :customer_id and (:status is null or status = :status)\n    order by case :sort when 'id' then id when 'status' then status end\n    limit :limit offset :offset": {
    params: { customer_id: CustomersId; status: "draft" | "confirmed" | null; sort: "id" | "status"; limit: number; offset: number };
    row: { id: OrdersId; status: "draft" | "confirmed"; note: string | null };
  };
  /** Orders whose note matches a pattern. No index serves LIKE, so this reads the table in full, and the build reports it. */
  "\n    -- Orders whose note matches a pattern. No index serves LIKE, so this\n    -- reads the table in full, and the build reports it.\n    select id, status, note from orders where note like :pattern order by id": {
    params: { pattern: string | null };
    row: { id: OrdersId; status: "draft" | "confirmed"; note: string | null };
  };
  /** Orders whose note matches a full-text query, best match first. */
  "\n    -- Orders whose note matches a full-text query, best match first.\n    select o.id, o.status, o.note, cast(bm25(order_search) as real) as score\n    from order_search join orders o on o.id = order_search.order_id\n    where order_search match :query\n    order by rank": {
    params: { query: string };
    row: { id: OrdersId; status: "draft" | "confirmed"; note: string | null; score: number | null };
  };
};

export const generated: Meta<Generated> = {
  "insert into orders (id, customer_id, status) values (:id, :customer_id, 'draft')": { params: ["id", "customer_id"], encode: [], json: [] },
  "insert into order_lines (id, order_id, sku, qty, price)\n       select value ->> 'id', :id, value ->> 'sku', value ->> 'qty', value ->> 'price' from json_each(:lines)": { params: ["id", "lines"], encode: ["lines"], json: [] },
  "select id, customer_id, status, note from orders where id = :id": { params: ["id"], encode: [], json: [] },
  "exists (select 1 from order_lines where order_id = :id)": { params: ["id"], encode: [], json: [] },
  "update orders set status = 'confirmed' where id = :id and status = 'draft'": { params: ["id"], encode: [], json: [] },
  "changes() = 1": { params: [], encode: [], json: [] },
  "update orders set note = :note where id = :id": { params: ["note", "id"], encode: [], json: [] },
  "select id, note, updated_at from orders where id = :id": { params: ["id"], encode: [], json: [] },
  "update order_lines\n       set price = (select value ->> 'price' from json_each(:lines) where value ->> 'id' = order_lines.id)\n       where order_id = :id and id in (select value ->> 'id' from json_each(:lines))": { params: ["lines", "id"], encode: ["lines"], json: [] },
  "changes() = json_array_length(:lines)": { params: ["lines"], encode: ["lines"], json: [] },
  "\n    -- One order, or none.\n    select id, customer_id, status, note from orders where id = :id": { params: ["id"], encode: [], json: [] },
  "\n    -- One order with its lines as an array. Empty when it has none.\n    select o.id, o.status,\n      coalesce(json_group_array(json_object('id', l.id, 'sku', l.sku, 'qty', l.qty, 'price', l.price))\n        filter (where l.id is not null), '[]') as lines\n    from orders o\n    left join order_lines l on l.order_id = o.id\n    where o.id = :id\n    group by o.id": { params: ["id"], encode: [], json: ["lines"] },
  "\n    -- The orders of one customer, newest id first.\n    select id, status from orders where customer_id = :customer_id order by id desc": { params: ["customer_id"], encode: [], json: [] },
  "\n    -- The orders with the given ids. One parameter carries the whole list,\n    -- so the list can be longer than the 100 bound values D1 allows.\n    select id, status from orders where id in (select value from json_each(:ids)) order by id": { params: ["ids"], encode: ["ids"], json: [] },
  "\n    -- Orders of one customer, with an optional status and a chosen order.\n    select id, status, note from orders\n    where customer_id = :customer_id and (:status is null or status = :status)\n    order by case :sort when 'id' then id when 'status' then status end\n    limit :limit offset :offset": { params: ["customer_id", "status", "sort", "limit", "offset"], encode: [], json: [] },
  "\n    -- Orders whose note matches a pattern. No index serves LIKE, so this\n    -- reads the table in full, and the build reports it.\n    select id, status, note from orders where note like :pattern order by id": { params: ["pattern"], encode: [], json: [] },
  "\n    -- Orders whose note matches a full-text query, best match first.\n    select o.id, o.status, o.note, cast(bm25(order_search) as real) as score\n    from order_search join orders o on o.id = order_search.order_id\n    where order_search match :query\n    order by rank": { params: ["query"], encode: [], json: [] },
};
