// Generated by solarsql analyze. Do not edit.
// Run solarsql analyze with the same source, catalog, and --out path after a change.
// Module schema.
import type { Meta, SqlValue } from "../../src/index.ts";

export type Generated = {
  "SELECT items.* FROM items WHERE EXISTS (SELECT 1 FROM json_each(items.labels) WHERE value = :label) ORDER BY items.id": {
    params: { label: SqlValue | null };
    row: { id: SqlValue | null; labels: SqlValue };
  };
  "SELECT items.* FROM items WHERE id IN (SELECT tagged.id FROM items AS tagged, json_each(tagged.labels) AS label WHERE label.value = :label) ORDER BY items.id": {
    params: { label: SqlValue | null };
    row: { id: SqlValue | null; labels: SqlValue };
  };
  "SELECT id, (SELECT cast(count(*) AS integer) FROM json_each(items.labels)) AS labelCount FROM items ORDER BY id": {
    params: {};
    row: { id: SqlValue | null; labelCount: number };
  };
};

export const generated: Meta<Generated> = {
  "SELECT items.* FROM items WHERE EXISTS (SELECT 1 FROM json_each(items.labels) WHERE value = :label) ORDER BY items.id": { params: ["label"], encode: [], json: [], reads: ["items"] },
  "SELECT items.* FROM items WHERE id IN (SELECT tagged.id FROM items AS tagged, json_each(tagged.labels) AS label WHERE label.value = :label) ORDER BY items.id": { params: ["label"], encode: [], json: [], reads: ["items"] },
  "SELECT id, (SELECT cast(count(*) AS integer) FROM json_each(items.labels)) AS labelCount FROM items ORDER BY id": { params: [], encode: [], json: [], reads: ["items"] },
};

export const statements = {
  ["byLabel"]: "SELECT items.* FROM items WHERE EXISTS (SELECT 1 FROM json_each(items.labels) WHERE value = :label) ORDER BY items.id",
  ["byLabelJoin"]: "SELECT items.* FROM items WHERE id IN (SELECT tagged.id FROM items AS tagged, json_each(tagged.labels) AS label WHERE label.value = :label) ORDER BY items.id",
  ["labelCounts"]: "SELECT id, (SELECT cast(count(*) AS integer) FROM json_each(items.labels)) AS labelCount FROM items ORDER BY id",
} as const;
